Update MinecraftSpigotServerCreator

diff --git a/MinecraftSpigotServerCreator b/MinecraftSpigotServerCreator
--- a/MinecraftSpigotServerCreator
+++ b/MinecraftSpigotServerCreator
@@ -4,15 +4,20 @@ then
   echo "Please type name of folder to new Minecraft Server in one argument!"
   exit 1
 else
+  if [[ -e "$1" ]]
+  then
+	echo "You can't create dir $1: folder or file exist of that name!"
+        exit 1
+  else
   mkdir $1
   cd $1
   touch eula.txt
   touch server.properties
-  # If you have laptop Mac change word xdg-open to open, but if you have Linux system operation, don't do anything about it.
-  xdg-open https://cdn.getbukkit.org/spigot/spigot-1.16.3.jar
-  echo "Please rename your downloaded file name to jarg.jar and wait 10 seconds."
-  sleep 10
+  open https://cdn.getbukkit.org/spigot/spigot-1.16.3.jar # BYŁO XDG-OPEN A NIE OPEN ALE NA GITHUBIE JEST NAPISANE ŻE SIE ZMIENIA NA MACU I LINUXIE
+  echo "Please rename your downloaded file name to jarg.jar and wait 30 seconds."
+  sleep 30
   mv ~/Downloads/jarg.jar ./jarg.jar
+  mv jarg.jar spigot-1.16.3.jar
   echo "eula=true">eula.txt
   echo "server-port: 25565">server.properties
   echo "motd: A Minecraft Server">>server.properties
@@ -60,4 +65,5 @@ else
   echo "use-native-transport=true">>server.properties
   echo "enable-jmx-monitoring=false">>server.properties
   echo "enable-rcon=false">>server.properties
+  fi
 fi
